variant: hybrid

batchSize: 32
nBatch: 2000
seed: 0
lr: 0.001
weightDecay: 0.0001
nClasses: 40
nInputFeatures: 256
strideLen: 4
kernelLen: 32
gaussianSmoothWidth: 2.0
modelDim: 512
numTransformerLayers: 2
numSSMLayers: 4
modelHeads: 8
dropout: 0.2
intermediateLayer: 3
timeMaskRatio: 0.6
channelDropProb: 0.3
featureMaskProb: 0.1
minTimeMask: 16
consistencyWeight: 0.2
intermediateLossWeight: 0.3
testTimeLR: 0.0001
enableTestTimeAdaptation: true
enableOnlineAdaptation: true
onlineAdaptationLR: 0.00001
diphoneContext: 40
transformerTimeMaskProb: 0.1
relPosMaxDist:
relBiasByHead: true
ffMult: 4
ssmDState: 16
ssmDConv: 4
